/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as ApiSubtitlesSearchRouteImport } from './routes/api/subtitles/search'
import { Route as ApiSubtitlesDownloadRouteImport } from './routes/api/subtitles/download'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubtitlesSearchRoute = ApiSubtitlesSearchRouteImport.update({
  id: '/api/subtitles/search',
  path: '/api/subtitles/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubtitlesDownloadRoute = ApiSubtitlesDownloadRouteImport.update({
  id: '/api/subtitles/download',
  path: '/api/subtitles/download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/subtitles/download': typeof ApiSubtitlesDownloadRoute
  '/api/subtitles/search': typeof ApiSubtitlesSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/subtitles/download': typeof ApiSubtitlesDownloadRoute
  '/api/subtitles/search': typeof ApiSubtitlesSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/watch/$id': typeof WatchIdRoute
  '/api/subtitles/download': typeof ApiSubtitlesDownloadRoute
  '/api/subtitles/search': typeof ApiSubtitlesSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/watch/$id'
    | '/api/subtitles/download'
    | '/api/subtitles/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/watch/$id' | '/api/subtitles/download' | '/api/subtitles/search'
  id:
    | '__root__'
    | '/'
    | '/watch/$id'
    | '/api/subtitles/download'
    | '/api/subtitles/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WatchIdRoute: typeof WatchIdRoute
  ApiSubtitlesDownloadRoute: typeof ApiSubtitlesDownloadRoute
  ApiSubtitlesSearchRoute: typeof ApiSubtitlesSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subtitles/search': {
      id: '/api/subtitles/search'
      path: '/api/subtitles/search'
      fullPath: '/api/subtitles/search'
      preLoaderRoute: typeof ApiSubtitlesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subtitles/download': {
      id: '/api/subtitles/download'
      path: '/api/subtitles/download'
      fullPath: '/api/subtitles/download'
      preLoaderRoute: typeof ApiSubtitlesDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WatchIdRoute: WatchIdRoute,
  ApiSubtitlesDownloadRoute: ApiSubtitlesDownloadRoute,
  ApiSubtitlesSearchRoute: ApiSubtitlesSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
